export const ch1Terms = [
"geology",
"physical geology",
"historical geology",
"uniformitarianism",
"catastrophism",
"hypothesis",
"theory",
"scientific method",
"hydrosphere",
"atmosphere",
"biosphere",
"geosphere",
"earth system science",
"system",
"nebular theory",
"solar nebula",
"crust",
"mantle",
"lithosphere",
"asthenosphere",
"transition zone",
"lower mantle",
"core",
"outter core",
"inner core",
"rock cycle",
"igneous rocks",
"sediment",
"sedimentary rock",
"metamorphic rock",
"ocean basin",
"continent",
"continental margin",
"continental shelf",
"continental slope",
"continental rise",
"deep-ocean basins",
"abyssal plain",
"deep-ocean trench",
"seamounts",
"oceanic ridge",
"oceanic ridge system",
"mid-ocean ridge",
"mountain belt",
"craton",
"sheild",
"stable platform",
]

export const ch2Terms = [
"ch2 first term",
"ch2 second term",
"ch2 third term",
"ch2 fourth term",
"ch2 fifth term",
]
export const ch3Terms = [
        "ch3 first term",
        "ch3 second term",
        "ch3 third term",
        "ch3 fourth term",
        "ch3 fifth term",
    ]
/*export const keyterms = {
    "chapter1":[
        {term:"geology", def:"test defintion"},
        {term:"physical geology", def:"test defintion"},
        {term:"historical geology", def:"test defintion"},
        {term:"uniformitarianism", def:"test defintion"},
        {term:"catastrophism", def:"test defintion"},
        {term:"hypothesis", def:"test defintion"},
        {term:"theory", def:"test defintion"},
        {term:"scientific method", def:"test defintion"},
        {term:"hydrosphere", def:"test defintion"},
        {term:"atmosphere", def:"test defintion"},
        {term:"biosphere", def:"test defintion"},
        {term:"geosphere", def:"test defintion"},
        {term:"earth system science", def:"test defintion"},
        {term:"system", def:"test defintion"},
        {term:"nebular theory", def:"test defintion"},
        {term:"solar nebula", def:"test defintion"},
        {term:"crust", def:"test defintion"},
        {term:"mantle", def:"test defintion"},
        {term:"lithosphere", def:"test defintion"},
        {term:"asthenosphere", def:"test defintion"},
        {term:"transition zone", def:"test defintion"},
        {term:"lower mantle", def:"test defintion"},
        {term:"core", def:"test defintion"},
        {term:"outter core", def:"test defintion"},
        {term:"inner core", def:"test defintion"},
        {term:"rock cycle", def:"test defintion"},
        {term:"igneous rocks", def:"test defintion"},
        {term:"sediment", def:"test defintion"},
        {term:"sedimentary rock", def:"test defintion"},
        {term:"metamorphic rock", def:"test defintion"},
        {term:"ocean basin", def:"test defintion"},
        {term:"continent", def:"test defintion"},
        {term:"continental margin", def:"test defintion"},
        {term:"continental shelf", def:"test defintion"},
        {term:"continental slope", def:"test defintion"},
        {term:"continental rise", def:"test defintion"},
        {term:"deep-ocean basins", def:"test defintion"},
        {term:"abyssal plain", def:"test defintion"},
        {term:"deep-ocean trench", def:"test defintion"},
        {term:"seamounts", def:"test defintion"},
        {term:"oceanic ridge", def:"test defintion"},
        {term:"oceanic ridge system", def:"test defintion"},
        {term:"mid-ocean ridge", def:"test defintion"},
        {term:"mountain belt", def:"test defintion"},
        {term:"craton", def:"test defintion"},
        {term:"sheild", def:"test defintion"},
        {term:"stable platform", def:"test defintion"},
    ],
    "chapter2":[
        {term: "ch2 term", def:"ch2 def"},
    ],
}*/

